#!/bin/bash

set -x

if [[ $2 == "up" || $2 == "dhcp4-change" ]]; then
  ADDR=(${IP4_ADDRESS_0//// }) # splits the variable by '/'
  NETWORK=(${IP4_ROUTE_0}) # splits the variable by ' '

  ip rule del lookup "$1" || true
  ip route flush table "$1"
  ip route add "$NETWORK" dev "$1" proto kernel scope link src "$ADDR" table "$1"
  ip route add default via "$IP4_GATEWAY" dev "$1" table "$1"
  ip rule add from "$ADDR" lookup "$1"
fi
